apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: mysql
  namespace: default
spec:
  rules:
  - services: ["mysql.default.svc.cluster.local"]
    methods: ["*"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: mysql
  namespace: default
spec:
  subjects:
  - user: "*"
#  - properties:
#      service: "apiserver"
#      namespace: "default"
  roleRef:
    kind: ServiceRole
    name: "mysql"
