apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: frontend
  namespace: default
spec:
  rules:
  - services: ["frontend.default.svc.cluster.local"]
    methods: ["GET", "POST"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: frontend
  namespace: default
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "frontend"
